회원가입, 비밀번호 인증코드 발행, 인증코드 이메일 전송기능 개발
wwwkang8/buridge pull request #12
Opened 2022-02-10 14:11 UTC by wwwkang8

## 개요 🧐

Fixes #(issue) [JIRA]

## 작업 사항 💻
- 회원가입 기능 : 이메일, 비밀번호, 닉네임, 상태코드, 권한 데이터로 사용자 정보를 만들고 회원가입
- 비밀번호 암호화 : Spring Security를 사용하여 비밀번호 암호화처리.
- 비밀번호 변경시 인증코드 6자리 발행 : 난수 발생기 사용하여 인증코드 6자리 발행
- 인증코드 이메일 전송 : 발행된 인증코드 6자리를 사용자 이메일에 전송

## 참고 문서 📘
-

## 체크 리스트 ✅

PR을 발행하기 이전에 아래의 항목을 확인해 주세요.

- [ X] 작성된 코드에 대해 테스트 코드를 적절히 추가, 변경, 삭제 하였습니까? 
    - 테스트 코드가 필요 없는 경우 간략히 설명해 주세요. @@ 테스트코드는 추가 예정
- [ ] 모든 테스트 코드가 성공 하였습니까? (명령어 : `./gradlew test`)
- [ O] 코드 스타일 검사를 통과 하였습니까? (명령어 : `./gradlew checkstyle`)

2022-02-11 04:44 UTC, parkhanbeen requested changes
생각보다 많은 코멘트를 달게 되었네요ㅎㅎ

2022-02-11 04:44 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/service/UserService.java
> +  PasswordEncoder passwordEncoder;
필드 주입 대신 생성자 주입을 고려해보는건 어떠신가요? ```private``` 제어자를 붙여주는게 좋을것 같아요

2022-02-11 04:44 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/service/UserService.java
> +  String sendGridApiKey;
```private``` 제어자를 붙여주는게 좋을것 같아요

2022-02-11 04:44 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/service/UserService.java
> +   * @version 1.0
```@author, @version```는 없어도 될것 같아요.
클래스나 메서드의 내용이나 목적을 간략하게만 적어주시면 될것 같아요.
[https://johngrib.github.io/wiki/java/javadoc/](url)

2022-02-11 04:44 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/service/UserService.java
> +        .role(Role.valueOf(userSignupDto.getRole()))
```Enum```타입을 그대로 받아서 넣는건 어떠신가요?

2022-02-11 04:44 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/service/UserService.java
> +    Random rnd = new Random();
축약어 대신 풀네임이나 의미있는 변수명을 사용하시는건 어떠신가요??

2022-02-11 04:44 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/service/UserService.java
> +    int secretCode = rnd.nextInt(999999);
```999999```가 의미하는게 무엇인가요? 의미있는 이름의 상수를 사용하는건 어떠신가요?

2022-02-11 04:44 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/service/UserService.java
> +    User user = userRepository.findUserByEmail(userSignupDto.getEmail());
```user``` 엔티티가 ```null```이면 어떻게 되나요??

2022-02-11 04:44 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/service/UserService.java
> +      System.out.println(userSignupDto.getEmail() + " 비밀번호 인증코드 전송완료");
```System.out.println```말고 ```logging``` 프레임워크를 사용하시는건 어떠신가요?

2022-02-11 04:44 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/service/UserService.java
> +      e.printStackTrace();
마찬가지로 ```logging``` 프레임워크를 사용하여 에러 로그를 찍어보는건 어떠신가요?

2022-02-11 04:44 UTC, parkhanbeen commented on src/main/java/com/realestate/service/web/user/UserRestController.java
> +  public void signup(@RequestBody UserSignupDto userSignupDto) {
```@Valid``` 어노테이션없이 검증이 가능한가요?

2022-02-11 04:44 UTC, parkhanbeen commented on src/main/java/com/realestate/service/web/user/UserRestController.java
> +  public void sendValidationCode(@RequestBody UserSignupDto userSignupDto) {
```UserSignupDto```는 회원가입 ```request dto```의 용도를 가지고 있는거 같은데 해당 request 
용 dto를 새로 만들어서 쓰는건 어떠신가요??

2022-02-11 16:44 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/service/UserService.java
> +    int secretCode = rnd.nextInt(999999);
999999은 상수를 출력하는 범위여서, 0~999999까지 6자리 정수를 출력하는 용도에요.

2022-02-11 16:45 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/service/UserService.java
> +  PasswordEncoder passwordEncoder;
네 확인해보니 필드 주입보단 생성자 주입을 더 권장하네요

2022-02-12 03:20 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/service/UserService.java
> +  String sendGridApiKey;
확인

2022-02-12 03:20 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/service/UserService.java
> +   * @version 1.0
확인

2022-02-12 03:23 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/service/UserService.java
> +        .role(Role.valueOf(userSignupDto.getRole()))
확인

2022-02-12 03:24 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/service/UserService.java
> +    Random rnd = new Random();
확인

2022-02-12 03:39 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/service/UserService.java
> +    User user = userRepository.findUserByEmail(userSignupDto.getEmail());
확인 --> orElseThrow로 예외처리

2022-02-12 03:58 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/service/UserService.java
> +      System.out.println(userSignupDto.getEmail() + " 비밀번호 인증코드 전송완료");
확인

2022-02-12 03:59 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/service/UserService.java
> +      e.printStackTrace();
확인

2022-02-12 04:29 UTC, wwwkang8 commented on src/main/java/com/realestate/service/web/user/UserRestController.java
> +  public void signup(@RequestBody UserSignupDto userSignupDto) {
확인

2022-02-12 04:37 UTC, wwwkang8 commented on src/main/java/com/realestate/service/web/user/UserRestController.java
> +  public void sendValidationCode(@RequestBody UserSignupDto userSignupDto) {
확인

2022-02-12 04:41 UTC, wwwkang8 commented
필드 주입 --> 생성자 주입은 다음 커밋 때 반영 예정입니다.

2022-02-12 04:41 UTC, merged