JWT 토큰 발행 및 인증로직을 추가하라
wwwkang8/buridge pull request #20
Opened 2022-02-21 13:14 UTC by wwwkang8

## 개요 🧐

Fixes #(issue) [JIRA]

## 작업 사항 💻
- JWT 토큰 발행 로직 추가
- JWT 토큰 검증 필터 추가
- ** 테스트 코드 작성은 진행중

## 참고 문서 📘
-

## 체크 리스트 ✅

PR을 발행하기 이전에 아래의 항목을 확인해 주세요.

- [ ] 작성된 코드에 대해 테스트 코드를 적절히 추가, 변경, 삭제 하였습니까?
    - 테스트 코드가 필요 없는 경우 간략히 설명해 주세요.
- [ ] 모든 테스트 코드가 성공 하였습니까? (명령어 : `./gradlew test`)
- [ ] 코드 스타일 검사를 통과 하였습니까? (명령어 : `./gradlew checkstyle`)

2022-02-22 07:38 UTC, parkhanbeen requested changes
우선 ```restDoc``` 테스트가 다 실패하고 있어요
아무래도 토큰을 토큰에 대한 로직을 모킹처리해서 해결해야 될것 같은데
찾아봐야겠네요ㅎㅎ

![image](https://user-images.githubusercontent.com/47877273/155084504-1c103d8c-020a-4d56-9757-a1bfc56a12ed.png)

2022-02-22 07:38 UTC, parkhanbeen commented on src/main/java/com/realestate/service/config/WebSecurityConfig.java
> +  }
어디서 쓰이는 메서드인가요?? 
```@Autowired```가 붙은 이유가 무엇인가요?

2022-02-22 07:38 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/jwt/JwtRequestFilter.java
> +      jwtToken = requestTokenHeader.substring(7);
```Bearer ```를 상수로 선언한 다음 
```substring(7)```은 ```substring(PREFIX.length())``` 처럼 사용하는건 어떠신가요??

2022-02-22 07:38 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/jwt/JwtRequestFilter.java
> +      jwtToken = requestTokenHeader.substring(7);
위에 같은 코드가 이미 사용되고 있어요
```suggestion
```

2022-02-22 07:38 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/jwt/JwtRequestFilter.java
> +        System.out.println("Unable to get JWT Token");
```logging``` 프레임워크를 사용하는게 더 좋을 것 같아요

2022-02-22 07:38 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/jwt/JwtRequestFilter.java
> +        System.out.println("JWT Token has expired");
마찬가지로 ```logging``` 프레임워크를 사용하는게 더 좋을 것 같아요

2022-02-22 07:38 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/jwt/JwtTokenUtil.java
> +  public String getUseremailFromToken(String token) {
이렇게 변경하는건 어떠신가요?
```suggestion
  public String getUserEmailFromToken(String token) {
```

2022-02-22 07:38 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/jwt/JwtUserDetailService.java
> +    if (findUser.get().getEmail().equals(email)) {
```findUser``` 에 유저 정보가 없으면 어떻게 되나요??

2022-02-22 07:38 UTC, parkhanbeen commented on src/main/java/com/realestate/service/web/user/UserRestController.java
> +    }
```catch```에서 가장 최상위 ```exception```으로 던지신 이유가 있으신가요?
그리고 ```throws```로 ```Exception```을 던지신 이유는 무엇인가요??

2022-02-22 07:38 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/service/PasswordEncoderService.java
> +  }
음 그냥 ```config```에서 빈등록하고 ```private final PasswordEncoder passwordEncoder```로
주입 받도록 하면 안되는건가용?? ```PasswordEncoderService```를 별도로 생성할 필요가 있을까싶어용...ㅎㅎ

2022-02-24 00:59 UTC, parkhanbeen approved these changes

2022-02-24 14:02 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/jwt/JwtRequestFilter.java
> +      jwtToken = requestTokenHeader.substring(7);
네 수정했어요.

2022-02-24 14:02 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/jwt/JwtRequestFilter.java
> +      jwtToken = requestTokenHeader.substring(7);
수정 완료했어요

2022-02-24 14:03 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/jwt/JwtRequestFilter.java
> +        System.out.println("Unable to get JWT Token");
수정 완료했어요

2022-02-24 14:03 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/jwt/JwtRequestFilter.java
> +        System.out.println("JWT Token has expired");
수정 완료 했어요

2022-02-24 14:03 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/jwt/JwtTokenUtil.java
> +  public String getUseremailFromToken(String token) {
네 CamelCase 반영할게요~

2022-02-24 14:09 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/jwt/JwtUserDetailService.java
> +    if (findUser.get().getEmail().equals(email)) {
Exception 처리 반영했어요

2022-02-24 14:16 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/service/PasswordEncoderService.java
> +  }
Config라는 것이 WebSecurityConfig에 선언하면 안되냐는 뜻일까요?

2022-02-24 15:24 UTC, wwwkang8 commented on src/main/java/com/realestate/service/config/WebSecurityConfig.java
> +  }
@Autowired는 AuthenticationManagerBuilder를 주입하기 위해서 사용되요. @Autowired는 스프링 빈을 주입받는 모든 메서드에서 사용 가능해요.
AuthenticationManager는 인메모리 인증, JDBC 인증, LDAP 인증이 가능합니다.

2022-02-24 15:25 UTC, merged

2022-02-25 05:39 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/service/PasswordEncoderService.java
> +  }
네 ```PasswordEncoderService```가 결국 ```PasswordEncoder```를 빈등록하는 ```config```의 용도로 밖에 안보여서
따로 작성할 필요가 있나 싶어서요ㅎㅎ