비밀번호 변경 기능 추가하라(키, 이메일 지우고 커밋)
wwwkang8/buridge pull request #27
Opened 2022-03-14 16:10 UTC by wwwkang8

## 개요 🧐

Fixes #(issue) [JIRA]

## 작업 사항 💻
- 비밀번호 변경 기능 추가
- 6자리 난수 발생 로직 수정

## 참고 문서 📘
-

## 체크 리스트 ✅

PR을 발행하기 이전에 아래의 항목을 확인해 주세요.

- [O] 작성된 코드에 대해 테스트 코드를 적절히 추가, 변경, 삭제 하였습니까?
    - RestDoc 테스트코드 작성 중 오류가 있어서, RestDoc 로직은 다음 커밋에서 추가해서 올릴 예정입니다.
- [ ] 모든 테스트 코드가 성공 하였습니까? (명령어 : `./gradlew test`)  
- [ ] 코드 스타일 검사를 통과 하였습니까? (명령어 : `./gradlew checkstyle`)

2022-03-15 11:29 UTC, parkhanbeen requested changes
![image](https://user-images.githubusercontent.com/47877273/158368399-3dd192eb-8a3f-4783-aa30-b0626526e506.png)
실패하는 테스트 수정 부탁드릴게용:)

2022-03-15 11:29 UTC, parkhanbeen commented on src/main/java/com/realestate/service/web/user/request/UserInfoRequest.java
> +  int secretCode;
`default` 제어자로 설정한 이유가 있을까요??

2022-03-15 11:29 UTC, parkhanbeen commented on src/main/java/com/realestate/service/web/user/response/UserInfoResponse.java
> +  String result;
`default` 제어자로 설정한 이유가 있을까요??

2022-03-15 11:29 UTC, parkhanbeen commented on src/test/resources/mock/user/userinfo_request.json
> +}
![image](https://user-images.githubusercontent.com/47877273/158368147-346ea069-4168-4074-9a85-ba985d3a8859.png)
공백 라인 추가 부탁드릴게용:)

2022-03-15 14:22 UTC, wwwkang8 commented on src/main/java/com/realestate/service/web/user/request/UserInfoRequest.java
> +  int secretCode;
UserInfoRequest 클래스 내부에서만 사용하는 변수라서 private 으로 수정했습니다

2022-03-15 14:22 UTC, wwwkang8 commented on src/main/java/com/realestate/service/web/user/response/UserInfoResponse.java
> +  String result;
UserInfoResponse 클래스 내부에서만 사용하는 변수라서 private 으로 수정했습니다

2022-03-15 14:23 UTC, wwwkang8 commented on src/test/resources/mock/user/userinfo_request.json
> +}
네 추가했습니다

2022-03-16 01:24 UTC, parkhanbeen approved these changes
고생하셧습니다

2022-03-17 14:17 UTC, merged