매물 목록 조회 엔드포인트와 RestDocs 문서를 작성하라
wwwkang8/buridge pull request #31
Opened 2022-03-20 04:58 UTC by parkhanbeen

## 개요 🧐

## 작업 사항 💻
- 매물 목록 조회 엔드포인트와 ``RestDocs``문서를 작성하였습니다.
- 테스트에 불필요한 메서드와 ``import``를 제거하였습니다.
- 매물 목록 조회 `dto` 클래스 필드명의 오타를 교정하였습니다.

## 참고 문서 📘
-

## 체크 리스트 ✅

PR을 발행하기 이전에 아래의 항목을 확인해 주세요.

- [ ] 작성된 코드에 대해 테스트 코드를 적절히 추가, 변경, 삭제 하였습니까?
    - 테스트 코드가 필요 없는 경우 간략히 설명해 주세요.
- [ ] 모든 테스트 코드가 성공 하였습니까? (명령어 : `./gradlew test`)
- [ ] 코드 스타일 검사를 통과 하였습니까? (명령어 : `./gradlew checkstyle`)

2022-03-20 14:10 UTC, wwwkang8 requested changes

2022-03-20 14:10 UTC, wwwkang8 commented on src/test/java/com/realestate/service/property/entity/PropertyCustomRepositoryImplTest.java
> +          assertThat(result.getContent().get(0).getResidentialType()).isEqualTo(HOUSING);
주거 타입이 HOUSING이 의미하는 것은 무엇인가요?
어떤 주거형식인지 명확한게 필요하지 않을까 싶어요.

2022-03-20 14:10 UTC, wwwkang8 commented on src/test/java/com/realestate/service/property/entity/PropertyCustomRepositoryImplTest.java
> +          assertThat(result.getContent().get(0).getResidentialType()).isEqualTo(OFFICE_HOTEL);
OFFICE_HOTEL이 의미하는 것은 오피스텔인가요??

2022-03-20 14:44 UTC, parkhanbeen commented on src/test/java/com/realestate/service/property/entity/PropertyCustomRepositoryImplTest.java
> +          assertThat(result.getContent().get(0).getResidentialType()).isEqualTo(HOUSING);
> 어떤 주거형식인지 명확한게 필요하지 않을까 싶어요.
주거 타입인 `Residentialtype`은 열거형으로 관리되고 있는데 `HOUSING`은 주택을 의미하고 있어요
어떤 주거형식인 명확하지 않다는 의미가 혹시 단어의 의미로 유추하기 힘들다는 뜻일까요?

![image](https://user-images.githubusercontent.com/47877273/159167863-7cd38197-4965-44c1-9045-fbd6e20c3591.png)
![image](https://user-images.githubusercontent.com/47877273/159167889-528ef353-7731-4faa-b7b0-f01a96d47d30.png)

2022-03-20 14:45 UTC, parkhanbeen commented on src/test/java/com/realestate/service/property/entity/PropertyCustomRepositoryImplTest.java
> +          assertThat(result.getContent().get(0).getResidentialType()).isEqualTo(OFFICE_HOTEL);
https://github.com/wwwkang8/buridge/pull/31#discussion_r830627028

2022-03-21 14:51 UTC, wwwkang8 commented on src/test/java/com/realestate/service/property/entity/PropertyCustomRepositoryImplTest.java
> +          assertThat(result.getContent().get(0).getResidentialType()).isEqualTo(HOUSING);
아 HOUSING은 단독주택을 의미하는 것인가보네요.
제가 헷갈렸던 부분은 주택이라고 하면 거주용인데 아파트, 오피스텔도 주택에 포함되는 개념이다보니까
그럼 주택의 의미는 뭔지 이해가 안되었어요.

2022-03-21 14:52 UTC, wwwkang8 approved these changes

2022-03-22 11:13 UTC, merged