현재 로그인된 사용자 정보 조회하는 어노테이션 개발하라
wwwkang8/buridge pull request #34
Opened 2022-03-28 17:45 UTC by wwwkang8

## 개요 🧐

Fixes #(issue) [JIRA]

## 작업 사항 💻
- 현재 로그인된 사용자 정보 조회 : @CurrentUser 어노테이션을 사용하여 조회가능

## 참고 문서 📘
-

## 체크 리스트 ✅

PR을 발행하기 이전에 아래의 항목을 확인해 주세요.

- [ ] 작성된 코드에 대해 테스트 코드를 적절히 추가, 변경, 삭제 하였습니까?
    - 테스트 코드가 필요 없는 경우 간략히 설명해 주세요.
- [ ] 모든 테스트 코드가 성공 하였습니까? (명령어 : `./gradlew test`)
- [ ] 코드 스타일 검사를 통과 하였습니까? (명령어 : `./gradlew checkstyle`)

2022-03-29 11:35 UTC, parkhanbeen requested changes

2022-03-29 11:35 UTC, parkhanbeen commented on src/main/java/com/realestate/service/user/jwt/JwtUserDetailService.java
> +      //return new User(findUser.getEmail(), findUser.getPassword(), new ArrayList<>());
주석처리 보다 제거하는건 어떠신가요??

2022-03-29 11:35 UTC, parkhanbeen commented on src/main/java/com/realestate/service/web/user/UserRestController.java
> +   * */
메서드 위에 `javaDoc`은 메서드에 대한 내용을 작성하는게 맞는거 같아요
`@CurrentUser`어노테이션에 대한 설명은 해당 어노테이션 위에 작성해 주시면 좋을것 같습니다:)

2022-03-29 11:35 UTC, parkhanbeen commented on src/main/java/com/realestate/service/web/user/UserRestController.java
> +  @GetMapping(value = "/currentUser")
해당 `API`의 용도는 무엇인가요??

2022-03-29 11:35 UTC, parkhanbeen commented on src/main/java/com/realestate/service/web/user/UserRestController.java
> +  public CurrentUserResponse loginUser(@CurrentUser User currentUser) {
`User` 엔티티를 사용해야 하는 이유가 있으신가요??
용도에 맞는 `dto`를 생성해서 사용하는건 어떠신가요?

2022-03-29 14:39 UTC, wwwkang8 commented on src/main/java/com/realestate/service/user/jwt/JwtUserDetailService.java
> +      //return new User(findUser.getEmail(), findUser.getPassword(), new ArrayList<>());
네 제거했어요

2022-03-29 15:21 UTC, wwwkang8 commented on src/main/java/com/realestate/service/web/user/UserRestController.java
> +  @GetMapping(value = "/currentUser")
이건 어노테이션이 잘 동작하는지 테스트를 하려고 만든 API였어요.

2022-03-29 15:22 UTC, wwwkang8 commented on src/main/java/com/realestate/service/web/user/UserRestController.java
> +  public CurrentUserResponse loginUser(@CurrentUser User currentUser) {
네 맞네요. User 엔티티를 사용하면 내부 DB를 보여주는 것과 같으니까, 이 부분은 LoginUserDto로 대체했어요

2022-03-29 15:34 UTC, wwwkang8 commented on src/main/java/com/realestate/service/web/user/UserRestController.java
> +  @GetMapping(value = "/currentUser")
이 어노테이션은 refresh 토큰 개발할 때 접속된 사용자를 가져오는 것으로 테스트를 대체할 예정이에요

2022-03-30 04:22 UTC, parkhanbeen approved these changes
고생하셨습니다!

2022-03-30 15:07 UTC, merged